Repository romancardenas/Group_E_Simulation_Lifecycle, pull requests merged in 2020-12, with the labels that each got.

#26 First draft of the function allow to run the simulation (run_sim)
  CMakeLists.txt
  data/config.json
  data/simulation_config.json
  include/simulation_lifecycle/convert.h
  include/simulation_lifecycle/error.h
  include/simulation_lifecycle/simulation.h
  src/main.c
  src/simulation_lifecycle/convert.c
  src/simulation_lifecycle/simulation.c
  test/data/convert_tests/case_7/messages.log
  test/data/convert_tests/case_7/structure.json
  test/data/run_simulation/1_1_nonexisting_model.json
  test/data/run_simulation/1_2_nonstring_model.json
  test/data/run_simulation/1_3_missing_model.json
  test/data/run_simulation/2_1_nonexisting_config_output_path.json
  test/data/run_simulation/2_2_invalid_config_output_path.json
  test/data/run_simulation/2_3_missing_config_output_path.json
  test/data/run_simulation/3_1_exist_result_output_path.json
  test/data/run_simulation/3_2_invalid_result_output_path.json
  test/data/run_simulation/3_3_missing_result_output_path.json
  test/data/run_simulation/4_1_valid_model_valid_result_output_path.json
  test/data/run_simulation/already_exists.txt
  test/data/run_simulation/config.json
  test/data/run_simulation/simulation_output_messages.txt
  test/test_convert.c
  test/test_run_sim.c
Labels: enhancement

#27 Build Simulation Scenario done
  CMakeLists.txt
  data/simulation_config.json
  include/simulation_lifecycle/convert.h
  include/simulation_lifecycle/error.h
  include/simulation_lifecycle/models.h
  include/simulation_lifecycle/simulation.h
  include/simulation_lifecycle/spatial_analysis.h
  include/simulation_lifecycle/structures.h
  include/simulation_lifecycle/utils/linked_list.h
  include/simulation_lifecycle/utils/workflow.h
  src/simulation_lifecycle/models.c
  src/simulation_lifecycle/simulation.c
  src/simulation_lifecycle/structures.c
  src/simulation_lifecycle/utils/linked_list.c
  src/simulation_lifecycle/utils/workflow.c
  test/data/DB_Ottawa_Vicinities_IncorrectID.geojson
  test/data/DB_Ottawa_Vicinities_IsolatedCell.geojson
  test/data/DB_Ottawa_Vicinities_Simple.geojson
  test/data/simulation/3_2_nonobject_default_config_model.json
  test/data/simulation/4_1_missing_cells_config.json
  test/data/simulation/4_2_nonarray_cells_config.json
  test/data/simulation/4_3_empty_cells_config.json
  test/data/simulation/4_4_cells_config_no_source.json
  test/data/simulation/4_5_cells_config_invalid_source.json
  test/data/simulation/4_6_cells_config_no_id_map.json
  test/data/simulation/4_7_cells_config_invalid_id_map.json
  test/data/simulation/4_8_cells_config_invalid_pop_mapping.json
  test/data/simulation/5_1_missing_vicinities_config.json
  test/data/simulation/5_2_empty_vicinities_config.json
  test/data/simulation/5_3_vicinities_config_invalid_source.json
  test/data/simulation/5_4_vicinities_config_invalid_id_map.json
  test/data/simulation/5_5_vicinities_config_incorrect_source.json
  test/data/simulation/5_6_vicinities_config_incomplete_source.json
  test/data/simulation/6_1_missing_output_config_path.json
  test/data/simulation/6_2_invalid_output_config_path.json
  test/data/simulation/6_3_existing_output_config_path.json
  test/data/simulation/6_4_valid_config.json
  test/data/simulation/output_config.json
  test/test_simulation.c
Labels: enhancement

#31 First release almost there
  data/DB_Ottawa_Vicinities_Simple.geojson
  data/results/build_simulation_output.json
  data/results/run_simulation_output.txt
  data/toy_workflow.json
  include/simulation_lifecycle/simulation.h
  include/simulation_lifecycle/spatial_analysis.h
  include/simulation_lifecycle/structures.h
  src/main.c
  src/simulation_lifecycle/models.c
  src/simulation_lifecycle/simulation.c
  src/simulation_lifecycle/structures.c
  src/simulation_lifecycle/utils/workflow.c
  test/data/run_simulation/simulation_output_messages.txt
  test/data/workflow/1_valid_workflow.json
Labels: enhancement

#34 - Made two changes to convert:
  data/demo_1/input/DB_Ottawa_Simple.geojson
  data/demo_1/input/DB_Ottawa_Vicinities_Simple.geojson
  data/demo_1/input/toy-model.geojson
  data/demo_1/output/structure.json
  data/demo_1/output/toy-model.geojson
  data/demo_1/output/visualization.json
  data/demo_1/scratch/build_simulation_output.json
  data/demo_1/scratch/run_simulation_output.txt
  data/demo_1/toy_workflow.json
  data/demo_2/input/provinces.geojson
  data/demo_2/input/provinces_vicinity.geojson
  data/demo_2/output/provinces.geojson
  data/demo_2/output/structure.json
  data/demo_2/output/visualization.json
  data/demo_2/provinces_workflow.json
  data/demo_2/scratch/build_simulation_output.json
  data/demo_2/scratch/run_simulation_output.txt
  include/simulation_lifecycle/convert.h
  include/simulation_lifecycle/error.h
  include/simulation_lifecycle/utils/workflow.h
  include/simulation_lifecycle/visualization.h
  src/main.c
  src/simulation_lifecycle/convert.c
  src/simulation_lifecycle/utils/workflow.c
  src/simulation_lifecycle/visualization.c
Labels: piou piou

#39 run_sim without changing directories
  data/DB_Ottawa_Simple_Example.geojson
  data/DB_Ottawa_Vicinities_Simple_Example.geojson
  data/results/simulation_output_messages.txt
  setup.sh
  src/simulation_lifecycle/simulation.c
  test/data/DB_Ottawa_Vicinities_IncorrectID.geojson
  test/data/DB_Ottawa_Vicinities_IsolatedCell.geojson
  test/data/DB_Ottawa_Vicinities_Simple.geojson
  test/data/run_simulation/3_1_exist_result_output_path.json
  test/data/run_simulation/3_2_invalid_result_output_path.json
  test/data/run_simulation/3_3_missing_result_output_path.json
  test/data/run_simulation/4_1_valid_model_valid_result_output_path.json
  test/data/simulation/output_config.json
  test/test_simulation.c
Labels: enhancement

#41 Enhanced CMake stuff
  .dockerignore
  .github/workflows/devel.yml
  .github/workflows/main.yml
  .gitignore
  CMakeLists.txt
  Dockerfile
  action.yml
  data/results/build_simulation_output.json
  data/results/run_simulation_output.txt
  run_tests.sh
  setup_docker.sh
  src/CMakeLists.txt
  src/main.c
  src/simulation_lifecycle/convert.c
  src/simulation_lifecycle/models.c
  src/simulation_lifecycle/simulation.c
  src/simulation_lifecycle/spatial_analysis.c
  src/simulation_lifecycle/spatial_analysis_operations/centroids.c
  src/simulation_lifecycle/spatial_analysis_operations/closest_distance.c
  src/simulation_lifecycle/spatial_analysis_operations/select_by_attributes.c
  src/simulation_lifecycle/utils/feature.c
  src/simulation_lifecycle/utils/file.c
  src/simulation_lifecycle/utils/workflow.c
  src/simulation_lifecycle/visualization.c
  test/CMakeLists.txt
  test/_test_template.c
  test/data/run_simulation/simulation_output_messages.txt
  test/test_feature.c
  test/test_run_sim.c
  test/test_simulation.c
  test/test_spatial_analysis.c
  test/test_workflow.c
Labels: enhancement

#48 Centroids function
  README.md
  include/simulation_lifecycle/error.h
  src/simulation_lifecycle/spatial_analysis_operations/centroids.c
  test/data/convert_tests/case_3/messages.log
  test/data/run_simulation/simulation_output_messages.txt
  test/data/spatial_operations/1_missing_data_source_workflow.json
  test/data/spatial_operations/2_existing_data_source_workflow.json
  test/test_spatial_operations.c
Labels: enhancement

#57 First review of header files
  README.md
  include/simulation_lifecycle/convert.h
  include/simulation_lifecycle/error.h
  include/simulation_lifecycle/models.h
  include/simulation_lifecycle/simulation.h
  include/simulation_lifecycle/spatial_analysis.h
  include/simulation_lifecycle/spatial_analysis_operations/centroids.h
  include/simulation_lifecycle/spatial_analysis_operations/closest_distance.h
  include/simulation_lifecycle/spatial_analysis_operations/select_by_atttributes.h
  include/simulation_lifecycle/structures.h
  include/simulation_lifecycle/utils/feature.h
  include/simulation_lifecycle/utils/file.h
  include/simulation_lifecycle/utils/linked_list.h
  include/simulation_lifecycle/utils/strings.h
  include/simulation_lifecycle/utils/workflow.h
  include/simulation_lifecycle/visualization.h
  test/data/visualization/provinces.geojson
  test/data/visualization/visualization.json
Labels: documentation

#58 Aidan code review
  src/simulation_lifecycle/spatial_analysis.c
  src/simulation_lifecycle/spatial_analysis_operations/centroids.c
  src/simulation_lifecycle/spatial_analysis_operations/select_by_attributes.c
  src/simulation_lifecycle/utils/feature.c
  src/simulation_lifecycle/utils/file.c
  src/simulation_lifecycle/utils/linked_list.c
  src/simulation_lifecycle/utils/workflow.c
  src/simulation_lifecycle/visualization.c
Labels: enhancement

#59 Closest Distance operation ready
  data/demo_1/demo.json
  data/demo_1/input/DA_Ottawa.geojson
  data/demo_1/input/DB_Ottawa_Simple.geojson
  data/demo_1/input/DB_Ottawa_Vicinities_Simple.geojson
  data/demo_1/input/toy-model.geojson
  data/demo_1/toy_workflow.json
  include/simulation_lifecycle/error.h
  src/simulation_lifecycle/convert.c
  src/simulation_lifecycle/spatial_analysis_operations/closest_distance.c
  test/data/Hospitals.geojson
  test/data/workflow/1_valid_workflow.json
Labels: enhancement

#61 Added two tests for data sources and params
  test/data/spatial_operations/10_missing_from_id_parameter_CD.json
  test/data/spatial_operations/11_missing_to_id_parameter_CD.json
  test/data/spatial_operations/12_invalid_geometry_origin_type_CD.json
  test/data/spatial_operations/13_invalid_geometry_destination_type_CD.json
  test/data/spatial_operations/7_missing_origin_data_source_CD.json
  test/data/spatial_operations/8_missing_destination_data_source_CD.json
  test/data/spatial_operations/9_missing_n_param_parameter_CD.json
  test/test_spatial_operations.c
Labels: enhancement
